[package]
name = "glue"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bumpalo = { version = "3", features = ["collections"] }
wide = "0.7"
rayon = "1"
crossbeam-deque = "0.8"
parking_lot = "0.12"
rustc-hash = "2.1"
hashbrown = "0.17"
clap = { version = "4.6", features = ["derive"] }
pastey = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[[bin]]
name = "glue"
path = "src/main.rs"

[lib]
name = "glue"
path = "src/lib.rs"
