//! ffi — Foreign Function Interface modules.
//!
//! Aggregates two FFI-related submodules:
//! - [`ExternC`]: `@extern("C")` extractor + Rust FFI wrapper generator. Scans
//!   the parsed AST, extracts extern C declarations, and generates C source
//!   files plus Rust FFI binding code.
//! - [`Ffi`]: Generated FFI bindings (auto-generated by `build.rs` from
//!   `builtin/*/Raw.glue`). Contains `bindings` and `wrapper` submodules
//!   included from `$OUT_DIR/ffi_generated.rs`. Empty when no `@extern("C")`
//!   `.glue` files are present under `builtin/`.

pub mod ExternC;
pub mod Ffi;
